Repository dcampogiani/ktmp, pull requests merged in 2020-05, with the labels that each got.

#15 Feature/2020 updates
  app/build.gradle
  app/build.gradle.kts
  build.gradle.kts
  common/build.gradle
  common/build.gradle.kts
  common/src/commonMain/kotlin/com/danielecampogiani/ktmp/ktor/KtorRequest.kt
  common/src/commonMain/kotlin/com/danielecampogiani/ktmp/sample/Api.kt
  gradle/wrapper/gradle-wrapper.properties
Labels: enhancement

#16 Setup CI with GitHub Actions
  .github/workflows/android.yml
  .github/workflows/swift.yml
Labels: ci

#12 Setup travis to run for android and iOS
  .travis.yml
Labels: ci

#14 [WIP] Add zip method
  app/src/test/java/com/danielecampogiani/ktmp/IntegrationRequestTest.kt
  app/src/test/java/com/danielecampogiani/ktmp/IntegrationResponseTest.kt
  app/src/test/java/com/danielecampogiani/ktmp/RequestTest.kt
  app/src/test/java/com/danielecampogiani/ktmp/UnitResponseTest.kt
  common/build.gradle
  common/src/commonMain/kotlin/com/danielecampogiani/ktmp/Request.kt
  common/src/commonMain/kotlin/com/danielecampogiani/ktmp/Response.kt
  common/src/commonMain/kotlin/com/danielecampogiani/ktmp/sample/Api.kt
  gradle/wrapper/gradle-wrapper.properties
Labels: common
